[package]
name = "FlexoAssistant"
version = "0.1.0"
edition = "2021"

[dependencies]
im = { version = "15.1.0" }
floem = "0.2.0"
regex = "1.11.1"
rust_decimal = "1.36"
rust_decimal_macros = "1.36"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
